### ISSUE TITLE
Please update cask to 5.4.0

### ISSUE THREAD

**Issue by seanwo** [OrangeDrangon/homebrew-apps#5]
I do my updates via brew, not in app notifications/updates (how I noticed there was a new version).

Can you also update the cask when you release an official version:
https://github.com/OrangeDrangon/android-messages-desktop/releases/tag/v5.4.0

Thanks for helping maintain this project from the original owner!

**Comment by OrangeDrangon** [comment]
Didn't know I needed to do that. Fixed
